export const badgeData = [
  {
    component: PersonalBadgesPopup,
    title: 'First Name',
    type: 'firstName',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/firstname.png`,
    placeholder: 'First Name Here',
  },
  {
    component: PersonalBadgesPopup,
    title: 'Last Name',
    type: 'lastName',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/lastname.png`,
    placeholder: 'Last Name Here',
  },
  {
    component: PersonalBadgesPopup,
    title: 'Date of Birth',
    type: 'dateOfBirth',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/dob.svg`,
    placeholder: 'MM/DD/YYYY',
  },
  {
    component: PersonalBadgesPopup,
    title: 'Current City',
    type: 'currentCity',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/currentcity-1.png`,
    placeholder: 'Current City here',
  },
  {
    component: PersonalBadgesPopup,
    title: 'Home Town',
    type: 'homeTown',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/hometown.svg`,
    placeholder: 'Hometown Here',
  },
  {
    component: PersonalBadgesPopup,
    title: 'Sex',
    type: 'sex',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/relationaship-1.png`,
    placeholder: 'Choose',
  },
  {
    component: PersonalBadgesPopup,
    title: 'Relationship Status',
    type: 'relationshipStatus',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/relationship.svg`,
    placeholder: 'Choose',
  },
  {
    component: WorkBadgePopup,
    title: 'Work',
    type: 'work',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/work-a.png`,
    placeholder: 'Work Here',
  },
  {
    component: EducationBadgePopup,
    title: 'Education',
    type: 'education',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/education-1.png`,
    placeholder: 'Education Here',
  },
  {
    component: PersonalBadgesPopup,
    title: 'ID / Passport',
    type: 'id-passport',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/Identity-2x-1.png`,
    placeholder: 'ID / Passport Here',
  },
  {
    component: PersonalBadgesPopup,
    title: 'Geolocation',
    type: 'geolocation',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/education-1.png`,
    placeholder: 'Geolocation',
  },
  {
    component: PersonalBadgesPopup,
    title: 'Security Question',
    type: 'security-question',
    logo: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/profile/securityquestion-a.png`,
    placeholder: 'Answer Here',
  },
];
